version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: codecapsule
    ports:
      - '3306:3306'